# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='pastScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('home_team', models.CharField(max_length=2)),
                ('home_score', models.CharField(max_length=2)),
                ('visitor_team', models.CharField(max_length=2)),
                ('visitor_score', models.CharField(max_length=2)),
                ('start_at', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.CharField(max_length=8)),
                ('home_team', models.CharField(max_length=2)),
                ('home_score', models.CharField(max_length=2)),
                ('visitor_team', models.CharField(max_length=2)),
                ('visitor_score', models.CharField(max_length=2)),
                ('start_at', models.CharField(max_length=5)),
                ('league', models.CharField(max_length=2)),
            ],
        ),
    ]
