# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npbapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pastScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('home_team', models.CharField(max_length=2)),
                ('home_score', models.IntegerField()),
                ('visitor_team', models.CharField(max_length=2)),
                ('visitor_score', models.IntegerField()),
                ('start_at', models.CharField(max_length=5)),
            ],
        ),
    ]
