# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npbapi', '0003_scores_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastscore',
            name='home_score',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='pastscore',
            name='visitor_score',
            field=models.CharField(max_length=2),
        ),
    ]
